Repository eunseopi/botox_front2, pull requests merged in 2024-07, with the labels that each got.

#5 [Refactoring] 모달 렌더링 방식 변경 제안
  .gitignore
  public/index.html
  src/pages/roompage/CreateRoomModal.js
Labels: Refactoring

#8 [코드수정]로그인 시 로그아웃 상태 변화.
  src/pages/mainpage/MainPage.js
Labels: documentation

#9 [API 연결] 게시판, 로그인 API 연결
  src/pages/loginpage/LoginPage.js
  src/pages/postpage/BoardPage.js
  src/pages/postpage/WritePage.js
  src/pages/roompage/voicechat/VoiceChat.js
Labels: documentation

#10 [Refactoring] API 로그인 토큰 에러
  src/pages/loginpage/LoginPage.js
Labels: Refactoring

#11 [modify] 로그인 토큰 에러
  src/pages/loginpage/LoginPage.js
Labels: bug

#12 [modify] 로그인 토큰 에러 수정2
  src/pages/loginpage/LoginPage.js
Labels: bug

#15 [modify] 로그인 토큰 에러 수정5
  src/pages/loginpage/LoginPage.js
Labels: bug

#16 [Documentation] 회원가입, 게시판 작성 api 수정
  src/pages/loginpage/SignUpPage.js
  src/pages/postpage/BoardPage.js
  src/pages/postpage/WritePage.js
Labels: documentation

#17 [Bug] 게시물 w.map 에러
  src/pages/postpage/BoardPage.js
Labels: bug

#18 [Bug] 게시물 w.map 에러 해결중
  src/pages/postpage/BoardPage.js
Labels: bug

#19 [Bug] 게시물 작성 해결중(1)
  src/pages/postpage/WritePage.js
Labels: bug

#20 [Bug] 게시물 작성 해결중(2번쨰)
  src/pages/postpage/WritePage.js
Labels: bug

#21 [Bug] 게시물 작성 해결중(3번째)
  src/pages/postpage/WritePage.js
Labels: bug

#22 [Bug] 게시물 작성 해결중(4번째)
  src/pages/postpage/WritePage.js
Labels: bug

#23 [Bug] 게시물 작성 해결중(5번째)
  src/pages/loginpage/LoginPage.js
  src/pages/postpage/WritePage.js
Labels: bug

#24 [Bug] 로그인 userInfo 문제 에러
  src/pages/loginpage/LoginPage.js
Labels: bug

#26 [Bug] 프로필 정보 불러오기 에러
  src/pages/postpage/BoardPage.js
  src/pages/roompage/modal/ProfileModal.js
Labels: bug

#27 [Bug] 게시글 작성 시 에러
  src/pages/postpage/WritePage.js
Labels: bug

#28 [Bug] 게시글 작성 시 에러 수정
  src/pages/postpage/WritePage.js
Labels: bug

#29 [Bug] 게시글 작성 시 에러 수정2
  src/pages/postpage/WritePage.js
Labels: bug

#30 [Bug] BoardPage username 에러
  src/pages/mainpage/MainPage.js
  src/pages/postpage/BoardPage.js
  src/pages/postpage/WritePage.js
Labels: bug

#31 [Bug] BoardPage username 에러 2
  src/pages/postpage/BoardPage.js
Labels: bug

#32 [Bug] BoardPage username 에러 3
  src/pages/postpage/BoardPage.js
Labels: bug

#33 [Bug] WritePage username 에러
  src/pages/postpage/WritePage.js
  src/pages/roompage/modal/ProfileModal.js
Labels: bug

#34 [Bug] 로그인, 로그아웃 상태 변화 에러
  src/pages/mainpage/MainPage.js
  src/pages/roompage/RoomPage.js
Labels: bug

#35 [Documentation] 게임 URL 별 RoomPage
  src/pages/roompage/RoomPage.js
Labels: documentation

#36 [Documentation] 게임 URL 별 RoomPage
  src/pages/roompage/RoomPage.js
Labels: documentation

#37 [Documentation] 게임 URL 별 RoomPage
  src/pages/roompage/RoomPage.js
Labels: documentation

#38 [Documentation] 게시글 수정,삭제 추가중
  src/pages/postpage/BoardPage.js
  src/pages/postpage/PostDetailPage.js
Labels: documentation

#39 [Documentation] 게시글 수정,삭제 추가중
  src/pages/postpage/PostDetailPage.js
Labels: documentation

#40 [Documentation] 게시글 수정,삭제 추가중
  src/pages/postpage/PostDetailPage.js
Labels: documentation

#41 [Bug] 게시글 수정,삭제 에러
  src/pages/postpage/PostDetailPage.js
Labels: bug

#42 [documentation] 페이징 수정
  src/pages/postpage/BoardPage.js
Labels: documentation

#43 [documentation] 페이징 수정
  src/pages/postpage/BoardPage.js
Labels: documentation

#44 [Bug] 게임 별 url Roompage
  src/App.js
  src/pages/roompage/RoomPage.js
Labels: bug

#45 [documentation] RoomPage 페이징 및 방 나가기 url 수정
  src/pages/roompage/RoomPage.js
  src/pages/roompage/textchat/TextChat.js
  src/pages/roompage/voicechat/VoiceChat.js
Labels: documentation

#46 [documentation] RoomPage 방 생성 API 연동
  src/pages/roompage/CreateRoomModal.js
Labels: documentation

#47 [documentation] RoomPage 방 생성 API 연동
  src/pages/roompage/CreateRoomModal.js
  src/pages/roompage/RoomPage.js
Labels: bug, documentation

#48 [Bug] RoomPage 방 생성 코드 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#49 [Bug] RoomPage 방 생성 시 BoardPage 에서 게시글 안보임
  src/pages/roompage/CreateRoomModal.js
  src/pages/roompage/RoomPage.js
Labels: bug

#50 [Bug] RoomPage 방 생성 시 BoardPage 에서 게시글 안보임
  src/pages/roompage/CreateRoomModal.js
Labels: bug

#51 [Bug] RoomPage 방 생성 시 BoardPage 에서 게시글 안보임
  src/pages/roompage/CreateRoomModal.js
Labels: bug

#52 [Bug] RoomPage 방 생성 시 BoardPage 에서 게시글 안보임
  src/pages/roompage/RoomPage.js
Labels: bug

#53 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#54 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/voicechat/VoiceChat.js
Labels: bug

#55 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/textchat/TextChat.js
  src/pages/roompage/voicechat/VoiceChat.js
Labels: bug

#56 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/CreateRoomModal.js
Labels: bug

#57 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/CreateRoomModal.js
  src/pages/roompage/RoomPage.js
Labels: bug

#58 [Bug] RoomPage 방 생성 시 보이지만 들어갔다가 나오면 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#59 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/CreateRoomModal.js
  src/pages/roompage/RoomPage.js
Labels: bug

#60 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#61 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#62 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#63 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#64 [Bug] RoomPage 방 생성 및 호출 에러
  src/pages/roompage/RoomPage.js
Labels: bug

#65 [documentation] 게임 url 별 게시판 보기
  src/pages/roompage/CreateRoomModal.js
  src/pages/roompage/RoomPage.js
  src/pages/roompage/voicechat/VoiceChat.js
Labels: documentation
